In [1]:
import SAC
from SAC import SAC
import os
import subprocess
import torch
from utils.logx import EpochLogger
from utils.logx import colorize
import itertools

Directory 'utils' already exists.


2025-05-18 12:21:37.124451: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
env_file = 'model_downloader.py'
env_url = "https://raw.githubusercontent.com/alibaniasad1999/master-thesis/main/Code/Python/utils/model_downloader.py"

if not os.path.isfile(env_file):
    print(f"Downloading {env_file} ...")
    subprocess.run(
        ['wget', '-q', '-O', env_file, env_url],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )
    print(f"{env_file} downloaded.")
else:
    print(f"{env_file} already exists.")

from Code.Python.TBP.PPO.Standard.model_downloader import download_everything

trajectory = download_everything('TBP')
from TBP import ThreeBodyEnv

model_downloader.py already exists.
trajectory.csv already exists.
Trajectory head:
   0.87018  -0.059444  0  -0.010472  -0.17514  0.1
0  0.87018  -0.059540  0  -0.010536  -0.17494    0
1  0.87017  -0.059636  0  -0.010600  -0.17474    0
2  0.87017  -0.059732  0  -0.010664  -0.17454    0
3  0.87016  -0.059828  0  -0.010728  -0.17434    0
4  0.87015  -0.059924  0  -0.010793  -0.17414    0
Data shape: (9999, 6)
TBP.py already exists.
trajectory.csv already exists.


In [9]:
import importlib
import SAC

# 2. When you’ve made changes to SAC.py on disk, reload it:
import importlib
importlib.reload(SAC)

# 3. Then pull in whatever you need from it:
from SAC import SAC

Directory 'utils' already exists.


In [10]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(colorize(f"Device is {device}! 🥰😎", 'green', bold=True))
# Define variables directly
env = ThreeBodyEnv(trajectory)
hid = 64
l = 2
gamma = 0.99
seed = 0
epochs = 50
exp_name = 'ddpg'
steps_per_epoch_=30000
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

ac_kwargs = dict(hidden_sizes=[hid]*l)
states_array = []
# logger_kwargs = setup_logger_kwargs(exp_name, seed)
reward_array=[]
# ddpg = DDPG(lambda : ThreeBodyEnv(trajectory, error_range=0.01, final_range=0.001), MLPActorCritic, ac_kwargs,seed_=seed, steps_per_epoch=steps_per_epoch_, epochs_=epochs, logger_kwargs_=logger_kwargs, device=device, batch_size=1024, start_steps=5000, update_after=1000, update_every=2000)


sac_rl = SAC(lambda : ThreeBodyEnv(trajectory, error_range=0.01, final_range=0.001), epochs=100, device_class=device, ac_kwargs_class=ac_kwargs, steps_per_epoch=steps_per_epoch_, batch_size=1024, start_steps=5000, update_after=1000, update_every=2000)

Device is cpu! 🥰😎
Logging data to /tmp/experiments/1747558551/progress.txt
Saving config:

{
    "ac_kwargs_class":	{
        "hidden_sizes":	[
            64,
            64
        ]
    },
    "actor_critic":	"MLPActorCritic",
    "alpha":	0.2,
    "batch_size":	1024,
    "device_class":	"cpu",
    "env_fn":	"<function <lambda> at 0x16cec3240>",
    "epochs":	100,
    "gamma":	0.99,
    "logger_kwargs":	null,
    "lr":	0.001,
    "max_ep_len":	30000,
    "num_test_episodes":	10,
    "num_updates":	10,
    "polyak":	0.995,
    "replay_size":	1000000,
    "save_freq":	1,
    "seed":	0,
    "self":	{
        "<SAC.SAC object at 0x16ceffa90>":	{
            "ac_kwargs":	{
                "hidden_sizes":	[
                    64,
                    64
                ]
            },
            "actor_critic":	"MLPActorCritic",
            "alpha":	0.2,
            "batch_size":	1024,
            "device":	"cpu",
            "env_fn":	"<function <lambda> at 0x16cec3240>",
            "

In [11]:
sac_rl.train()

[ 0.01001916 -0.00028724  0.03104664 -0.01062203]
idx 0.02067 state 0.0343101595764025
too much error 🥲😱
second player was in the game
updating 🥰
[ 0.01001521 -0.00040661  0.03046805 -0.01172578]
idx 0.02123 state 0.03415063389017057
too much error 🥲😱
second player was in the game
[ 0.00999437 -0.00034293  0.03069369 -0.01146411]
idx 0.0209 state 0.034256873043217874
too much error 🥲😱
second player was in the game
updating 🥰
[ 0.01001502 -0.00036357  0.03114273 -0.0116027 ]
idx 0.0211 state 0.034712032637315315
too much error 🥲😱
second player was in the game
[ 0.00999982  0.00012921  0.03421652 -0.01011714]
idx 0.01982 state 0.03705590750421994
too much error 🥲😱
second player was in the game
updating 🥰
[ 0.01001628  0.00038222  0.03479729 -0.01114212]
idx 0.01958 state 0.03788759931119618
too much error 🥲😱
second player was in the game
[ 0.01001089  0.00029506  0.03397196 -0.0112097 ]
idx 0.01995 state 0.03714910918093263
too much error 🥲😱
second player was in the game
updating 🥰
[ 0.0

KeyboardInterrupt: 